/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDlZYMth7gvpJYiqBDxMe6QA",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "koreanenglish": a.model({
        id: a.integer().required(),
        korean: a.string(),
        english: a.string(),
        symbol: a.string()
    }).identifier([
        "id"
    ])
});
